### ISSUE TITLE
Node labels

### ISSUE THREAD

**Issue by mbwatson** [NeuroBridge/client#2]
we want to see the terms associated with each of the nodes, all at once.

if there are a large enough amount of node in view, this could get busy, so we will also provide a toggle switch so they can be shown and hidden as necessary.

use only the`label` property for label text.

**Comment by HowardLander** [comment]
Looks like right now the labels appear in the upper right corner of the node.  However in left to right mode this looks a bit odd.  Maybe the labels, particularly for the last level, should appear centered to the right of the node.

**Comment by mbwatson** [comment]
on staging, you should now see offset labels for nodes with children and vertically centered labels for leaf nodes, as shown in this screenshot:

![Screenshot from 2021-09-29 17-25-29](https://user-images.githubusercontent.com/6019870/135350821-fa58afd0-f62a-478f-b876-398f3247a634.png)

thoughts?

**Comment by HowardLander** [comment]
Hi Matt,

This does look better, though I wonder about the placement of the "TaskParadigmImagingProtocol" label.

Also, is Lei on this mailing list?

Howard

________________________________

**Comment by mbwatson** [comment]
@HowardLander 

how about a little more control for the label palcement?

![Peek 2021-09-30 13-36](https://user-images.githubusercontent.com/6019870/135503811-996af35a-9a76-45d7-bc66-e6ce2a2f3371.gif)

**Comment by HowardLander** [comment]
@mbwatson Yeah, I like this.  One other thing: can we do something to make sure the nodes don't overlap

![image](https://user-images.githubusercontent.com/1263277/135509878-71602af5-d173-4ba2-a038-7b9ed3219072.png)

**Comment by mbwatson** [comment]
@HowardLander yeah that has been bugging me a little bit, too. i've added some collision detection to prevent node overlap
![Peek 2021-09-30 14-59](https://user-images.githubusercontent.com/6019870/135514892-e4770328-4bd8-4a4d-b6ca-f0061873cca8.gif)

**Comment by HowardLander** [comment]
Yeah, this seems a bit better. Thanks
